openapi: 3.0.0

info:
  description: ""
  version: 0.0.1
  title: Financial API documentation
  contact:
    name: JeyServer
    url: http://www.jeyserver.com
    email: info@jeyserver.com

servers:
  - url: '{schema}://{domain}/{language}'
    description: Financial API documentation sample
    variables:
      schema:
        enum:
          - 'http'
          - 'https'
        default: 'https'
      domain:
        default: some-test-domain.com
      language:
        default: fa

paths:
  /userpanel/transactions:
    get:
      tags:
        - Transaction
      summary: Search and get list of transactions
      description: ""
      parameters:

        - in: query
          name: api
          schema:
            type: boolean
            enum:
              - true
          required: true
          description: "you should pass this option or 'ajax' option in order to get json result"
        
        - in: query
          name: ajax
          schema:
            type: boolean
            enum:
              - true
          description: "you should pass this option or 'api' option in order to get json result"

        - in: query
          name: ipp
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 25
          description: "Items per page"

        - in: query
          name: page
          schema:
            type: integer
            format: int32
            minimum: 1
          description: "the page number"

        - in: query
          name: id
          schema:
            type: integer
            format: int32
          description: "The ID of the transaction you search for it"

        - in: query
          name: title
          schema:
            type: string
          description: "The transaction title you search for it"

        - in: query
          name: user
          schema:
            type: integer
            format: int32
          description: "The ID of user that owns transaction"

        - in: query
          name: status
          schema:
            $ref: "./models/financial/Transaction/TransactionStatus.yaml#/components/schemas/TransactionStatus"
          description: "status of the transaction"

        - in: query
          name: download
          schema:
            type: string
            enum:
              - csv
            description: |
              if you pass this option, the search result will be downloaded in the given format
              the available formats is
              * `csv` - Comma-separated values

        - in: query
          name: word
          schema:
            type: string
          description: "in case you search for something, pass this option"

        - in: query
          name: create_from
          schema:
            type: string
          description: "search by create_from, the format should ne like: 'Y/m/d H:i:s'"

        - in: query
          name: create_to
          schema:
            type: string
          description: "search by create_to, the format should ne like: 'Y/m/d H:i:s'"

        - in: query
          name: comparison
          schema:
            type: string
            enum:
              - contains
              - equals
              - startswith
          description: "the types of comparison in search"

      responses:
        "200":
          description: sucessfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    enum:
                      - true

                  items:
                    type: array
                    items:
                      $ref: "./models/financial/Transaction.yaml#/components/schemas/Transaction"

                  items_per_page:
                    type: integer
                    format: int32
                    minimum: 0

                  current_page:
                    type: integer
                    format: int32
                    minimum: 0

                  total_items:
                    type: integer
                    format: int32
                    minimum: 0

                  balance:
                    type: object
                    properties:
                      amount:
                        type: number
                        format: double
                      currency:
                        $ref: "./models/financial/Currency.yaml#/components/schemas/Currency"

                  debt:
                    type: object
                    properties:
                      amount:
                        type: number
                        format: double

                      currency:
                        $ref: "./models/financial/Currency.yaml#/components/schemas/Currency"

                      error:
                        type: array
                        items:
                          $ref: "./models/base/view/Error.yaml#/components/schemas/Error"
        "403":
          description: your session is revoked or you have not permission to access this route
        "5XX":
          description: Unexpected error.

  /userpanel/transactions/refund/add:
    post:
      tags:
        - Transaction
      summary: create new refund transaction
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:

                refund_user:
                  type: integer
                  format: int32
                  description: "if you can access to create refund transaction for another user, pass the id of the user, else this will be ignored"

                refund_price:
                  type: number
                  format: double
                  description: "the amount of refund request, the currency of this amount is based on user's currency"

                refund_account:
                  type: integer
                  format: int32
                  description: "the id of bank account that you request for refund to this bank account"
      responses:
        "200":
          description: sucessfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: "if true, the result is ok, if false, some input is not valid!"
                  redirect:
                    type: string
                    description: "the url of created transaction for refund"
        "403":
          description: your session is revoked or you have not permission to access this route
        "5XX":
          description: Unexpected error.

  /userpanel/settings/financial/banks/accounts:
    get:
      tags:
        - BankAccount
      summary: Search and get list of bank accounts
      description: ""
      parameters:

        - in: query
          name: api
          schema:
            type: boolean
            enum:
              - true
          required: true
          description: "you should pass this option or 'ajax' option in order to get json result"
        
        - in: query
          name: ajax
          schema:
            type: boolean
            enum:
              - true
          description: "you should pass this option or 'api' option in order to get json result"

        - in: query
          name: ipp
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 25
          description: "Items per page"

        - in: query
          name: page
          schema:
            type: integer
            format: int32
            minimum: 1
          description: "the page number"

        - in: query
          name: id
          schema:
            type: integer
            format: int32
          description: "The ID of the transaction you search for it"

        - in: query
          name: bank
          schema:
            type: integer
            format: int32
          description: "The ID of bank that the bankaccount is exists in"

        - in: query
          name: user
          schema:
            type: integer
            format: int32
          description: "The ID of user that owns bankaccount"

        - in: query
          name: account
          schema:
            type: string
          description: "the account number of bank account"

        - in: query
          name: cart
          schema:
            type: string
          description: "the card number of bank account"

        - in: query
          name: shaba
          schema:
            type: string
          description: "the shaba of bank account"

        - in: query
          name: owner
          schema:
            type: string
          description: "the owner name of bank account"

        - in: query
          name: status
          schema:
            $ref: "./models/financial/Bank/Account/AccountStatus.yaml#/components/schemas/AccountStatus"
          description: "status of the transaction"

        - in: query
          name: word
          schema:
            type: string
          description: "in case you search for something, pass this option"

        - in: query
          name: comparison
          schema:
            type: string
            enum:
              - contains
              - equals
              - startswith
          description: "the types of comparison in search"

      responses:
        "200":
          description: sucessfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    enum:
                      - true

                  items:
                    type: array
                    items:
                      $ref: "./models/financial/Bank/Account.yaml#/components/schemas/Account"

                  items_per_page:
                    type: integer
                    format: int32

                  current_page:
                    type: integer
                    format: int32

                  total_items:
                    type: integer
                    format: int32
        "403":
          description: your session is revoked or you have not permission to access this route
        "5XX":
          description: Unexpected error.

  /userpanel/transactions/user-stats:
    get:
      tags:
        - Transaction
      summary: get chart data for spend and gain of user
      description: ""
      parameters:

        - in: query
          name: api
          schema:
            type: boolean
            enum:
              - true
          required: true
          description: "you should pass this option or 'ajax' option in order to get json result"

        - in: query
          name: ajax
          schema:
            type: boolean
            enum:
              - true
          description: "you should pass this option or 'api' option in order to get json result"

        - in: query
          name: type
          schema:
            type: string
            enum:
              - gain
              - spend
          required: true
          description: "the type of chart"

        - in: query
          name: from
          schema:
            type: string
          required: true
          description: "the start of chart, should be in format: 'Y/m/d H:i:s'"

        - in: query
          name: to
          schema:
            type: string
          description: "the end of chart, should be in format: 'Y/m/d H:i:s'"

        - in: query
          name: interval
          schema:
            type: string
            enum:
              - 1D
              - 1M
              - 1Y
          required: true
          description: "the interval of the chart, it can be daily (1D), monthly (1M) and yearly (1Y)"

        - in: query
          name: limit
          schema:
            type: number
            format: int32
            default: 6
          description: "the count of chart data"

      responses:
        "200":
          description: sucessfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    enum:
                      - true

                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        unix:
                          type: number
                          format: int32
                          x-faker: time.recent
                        sum:
                          type: number
                          format: double
                          minimum: 0
        "403":
          description: your session is revoked or you have not permission to access this route
        "5XX":
          description: Unexpected error.

  /userpanel/transactions/merge:
    post:
      tags:
        - Transaction
      summary: merge transaction into one transaction
      description: ""
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:

                transactions:
                  type: array
                  items:
                    type: number
                    format: int32
                  description: "the id of transactions you want to merge it in one transaction, remind transactions should have same user to merge!"

                title:
                  type: string
                  description: "title of new transaction that will contains merged transactions"

                expire_at:
                  type: number
                  format: int32
                  description: "the expire date of new transaction"
      responses:
        "200":
          description: sucessfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  transaction:
                    $ref: "./models/financial/Transaction.yaml#/components/schemas/Transaction"
        "403":
          description: your session is revoked or you have not permission to access this route
        "5XX":
          description: Unexpected error.

 